# Setup
title:               Программирование на C++ и Python
#tagline:             'A Jekyll theme'
#description:         ''
#url:                 http://nsu-programming.github.io
#baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  email:             vit.vorobiev@gmail.com

# Gems
plugins:
  - jekyll-paginate
